// The buildInfo constant is generated by sbt. Do not edit directly.
const buildInfo = { latestVersion: '0.17.1', latestMinorVersion: '0.17' };

const repoUrl = "https://github.com/ovotech/fs2-kafka";

// See https://docusaurus.io/docs/site-config for available options.
const siteConfig = {
  title: 'FS2 Kafka',
  tagline: 'Functional Kafka Streams for Scala',
  url: 'https://ovotech.github.io/fs2-kafka',
  baseUrl: '/fs2-kafka/',

  customDocsPath: 'out',

  projectName: 'fs2-kafka',
  organizationName: 'ovotech',

  headerLinks: [
    { doc: 'overview', label: 'Documentation' },
    { href: repoUrl, label: "GitHub" }
  ],

  headerIcon: 'img/fs2-kafka.white.svg',
  titleIcon: 'img/fs2-kafka.svg',
  favicon: 'img/favicon.png',

  colors: {
    primaryColor: '#122932',
    secondaryColor: '#153243',
  },

  copyright: `Copyright © 2018 OVO Energy Limited.`,

  highlight: { theme: 'github' },

  onPageNav: 'separate',

  cleanUrl: true,

  repoUrl,

  buildInfo
};

module.exports = siteConfig;
