// The buildInfo constant is generated by sbt. Do not edit directly.
const buildInfo = { organization: 'com.ovoenergy', moduleName: 'fs2-kafka', latestVersion: '0.19.2', scalaMinorVersion: '2.12', scalaPublishVersions: '2.11 and 2.12' };

const repoUrl = "https://github.com/ovotech/fs2-kafka";

const apiUrl = `https://oss.sonatype.org/service/local/repositories/releases/archive/com/ovoenergy/fs2-kafka_${buildInfo.scalaMinorVersion}/${buildInfo.latestVersion}/fs2-kafka_${buildInfo.scalaMinorVersion}-${buildInfo.latestVersion}-javadoc.jar/!/fs2/kafka/index.html`

// See https://docusaurus.io/docs/site-config for available options.
const siteConfig = {
  title: 'FS2 Kafka',
  tagline: 'Functional Kafka Streams for Scala',
  url: 'https://ovotech.github.io/fs2-kafka',
  baseUrl: '/fs2-kafka/',

  customDocsPath: 'docs/target/mdoc',

  projectName: 'fs2-kafka',
  organizationName: 'ovotech',

  headerLinks: [
    { href: apiUrl, label: 'API Docs' },
    { doc: 'overview', label: 'Documentation' },
    { href: repoUrl, label: "GitHub" }
  ],

  headerIcon: 'img/fs2-kafka.white.svg',
  titleIcon: 'img/fs2-kafka.svg',
  favicon: 'img/favicon.png',

  colors: {
    primaryColor: '#122932',
    secondaryColor: '#153243',
  },

  copyright: `Copyright © 2018-${new Date().getFullYear()} OVO Energy Limited.`,

  highlight: { theme: 'github' },

  onPageNav: 'separate',

  cleanUrl: true,

  repoUrl,

  buildInfo,

  apiUrl
};

module.exports = siteConfig;
