// The buildInfo constant is generated by sbt. Do not edit directly.
const buildInfo = { organization: 'com.ovoenergy', coreModuleName: 'fs2-kafka', latestVersion: '0.20.0-M2', scalaMinorVersion: '2.12', scalaPublishVersions: '2.12 and 2.13', vulcanModuleName: 'fs2-kafka-vulcan' };

const repoUrl = "https://github.com/ovotech/fs2-kafka";

const apiUrl = "/fs2-kafka/api/fs2/kafka/index.html";

// See https://docusaurus.io/docs/site-config for available options.
const siteConfig = {
  title: "FS2 Kafka",
  tagline: "Functional Kafka Streams for Scala",
  url: "https://ovotech.github.io/fs2-kafka",
  baseUrl: "/fs2-kafka/",

  customDocsPath: "docs/target/mdoc",

  projectName: "fs2-kafka",
  organizationName: "ovotech",

  headerLinks: [
    { href: apiUrl, label: "API Docs" },
    { doc: "overview", label: "Documentation" },
    { href: repoUrl, label: "GitHub" }
  ],

  headerIcon: "img/fs2-kafka.white.svg",
  titleIcon: "img/fs2-kafka.svg",
  favicon: "img/favicon.png",

  colors: {
    primaryColor: "#122932",
    secondaryColor: "#153243"
  },

  copyright: `Copyright © 2018-${new Date().getFullYear()} OVO Energy Limited.`,

  highlight: { theme: "github" },

  onPageNav: "separate",

  separateCss: ["api"],

  cleanUrl: true,

  repoUrl,

  buildInfo,

  apiUrl
};

module.exports = siteConfig;
